import { useEffect } from 'react';
import { useSearchParams, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import axios from 'axios';

export const SSOHandler = () => {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const location = useLocation();
  const { loginWithToken } = useAuth();

  useEffect(() => {
    const tokenParam = searchParams.get('token');
    const magicTokenParam = searchParams.get('magic_token');
    const apiKey = searchParams.get('api_key') || '';

    const authenticate = async () => {
      try {
        let finalJwt = null;
        let magicTokenToExchange = magicTokenParam;

        if (tokenParam) {
          // Check if tokenParam is a valid JWT (contains dots and is long enough)
          // Otherwise, it's a GUID magic link generated by the .NET backend
          if (tokenParam.length > 100 && tokenParam.includes('.')) {
            finalJwt = tokenParam;
          } else {
            magicTokenToExchange = tokenParam;
          }
        }

        // If magic_token is provided, exchange it via API
        if (magicTokenToExchange && !finalJwt) {
          const apiBase = import.meta.env.VITE_API_BASE_URL || 'https://staging-api.sahldesk.com/api/v1';
          const res = await axios.post(`${apiBase}/Users/magic-login`, { token: magicTokenToExchange });
          if (res.data && res.data.token) {
            finalJwt = res.data.token;
          }
        }

        if (finalJwt) {
          await loginWithToken(finalJwt, apiKey);
          
          // Clean sensitive tokens from URL without full reload
          const cleanSearch = new URLSearchParams(location.search);
          cleanSearch.delete('token');
          cleanSearch.delete('magic_token');
          cleanSearch.delete('api_key');
          
          const cleanPath = location.pathname + (cleanSearch.toString() ? `?${cleanSearch.toString()}` : '');
          navigate(cleanPath, { replace: true });
        }
      } catch (err) {
        console.error('Magic Link / SSO Authentication failed:', err);
        navigate('/login?from=sso_catch', { replace: true });
      }
    };

    if (tokenParam || magicTokenParam) {
      authenticate();
    }
  }, [searchParams]);

  return null;
};
